# Generated by Django 4.2.7 on 2023-12-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AaTrajectoryPDBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AaTrajectoryPDB', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CaTrajectoryPDBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaTrajectoryPDB', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StructurePDBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StructurePDB', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
