# Generated by Django 4.2.7 on 2023-12-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrimd', '0002_jobmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AaTrajectoryPDBModel',
        ),
        migrations.DeleteModel(
            name='CaTrajectoryPDBModel',
        ),
        migrations.DeleteModel(
            name='StructurePDBModel',
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='Domains',
            field=models.CharField(default=',', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='Example',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
