# Generated by Django 4.2.8 on 2024-01-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrimd', '0004_jobmodel_cnasourcenode_jobmodel_cnatargetnode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='SampledCaTrajPDBPath',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
