# Generated by Django 4.2.8 on 2024-01-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrimd', '0005_jobmodel_sampledcatrajpdbpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='CNAStatus',
            field=models.CharField(blank=True, default='Right', max_length=20),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='EHHStatus',
            field=models.CharField(blank=True, default='Right', max_length=20),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='PRSStatus',
            field=models.CharField(blank=True, default='Right', max_length=20),
        ),
    ]
